### ISSUE TITLE
[GUI] The template list displayed in the creation of device is not complete

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1022]
There are 21 registered models, but only **20** models are shown in the list of models to be selected in the creation of the device.

- template list

![Screenshot_59](https://user-images.githubusercontent.com/37310063/55351615-335b6a00-5495-11e9-8bf7-c3bfc444428b.png)

![Screenshot_60](https://user-images.githubusercontent.com/37310063/55351790-9fd66900-5495-11e9-99e1-a340b94b0dc0.png)

- templates registered

![Screenshot_55](https://user-images.githubusercontent.com/37310063/55351716-6c93da00-5495-11e9-8387-5f75eabd000f.png)

![Screenshot_56](https://user-images.githubusercontent.com/37310063/55351727-71f12480-5495-11e9-8093-f7d233a1d37a.png)

![Screenshot_57](https://user-images.githubusercontent.com/37310063/55351738-761d4200-5495-11e9-8992-71a018f969a0.png)

![Screenshot_58](https://user-images.githubusercontent.com/37310063/55351746-79b0c900-5495-11e9-9d95-3a219079db63.png)

**Note**: the list of templates is not sorted by label

**Comment by cfrancisco** [comment]
I reproduced the dataset and got a curious thing. 
When you do a request with query string as:
      "/template?page_size=36&page_num=1&sortBy=label"
There're 21 elements with the following pagination information: 
    "pagination": {
        "has_next": false, 
        "next_page": null, 
        "page": 1, 
        "total": 1
     }, 

But, when do a simple request as:  "/template"
There're 20 elements and the pagination shows:
  "pagination": {
    "has_next": true, 
    "next_page": 2, 
    "page": 1, 
    "total": 2
  }, 

It sounds as the template URI is automatically paginating the templates, even if the page_num and page_size are empty (checking the API documentation, these fields are optional).

**Comment by giovannicuriel** [comment]
This was tested using baseline 58.2-20190321?

**Comment by giovannicuriel** [comment]
By the way, @cfrancisco, I think this behaviour is correct (but poorly documented): the default pagination is 20 items per page.

**Comment by giovannicuriel** [comment]
What we could do:

- Add a "singlePage" item in query string to force the response to be generated all at once. This is problematic because it might generate a *huge* response (which is difficult to recommend).
- Implement pagination in template selection.

**Comment by mprevide** [comment]
I will implement pagination in template

**Comment by cfrancisco** [comment]
@giovannicuriel and requires  page_num and page_size as mandatory fields?

**Comment by betefaber** [comment]
Test OK.

- request

![image](https://user-images.githubusercontent.com/37310063/56768902-fded2800-6785-11e9-8733-c65817225008.png)

- response

![image](https://user-images.githubusercontent.com/37310063/56768971-34c33e00-6786-11e9-894a-6321513a10bf.png)

**Comment by betefaber** [comment]
There are 24 registered templates, but only **20** templates are shown in the creation of the device.

![Screenshot at 2019-07-04 16-28-26](https://user-images.githubusercontent.com/37310063/60686768-1dd55200-9e81-11e9-800e-92c5d16ce4f8.png)

Note that there are two ways to request templates: with pagination (20 templates per page) and no pagination.

- **with pagination**: templates list and templates filter

![Screenshot at 2019-07-04 16-29-46](https://user-images.githubusercontent.com/37310063/60687183-5f66fc80-9e83-11e9-8fe7-4af56c05acbc.png)

- **without pagination**

![Screenshot at 2019-07-04 16-30-18](https://user-images.githubusercontent.com/37310063/60687019-4e69bb80-9e82-11e9-9ecf-4498f6033be1.png)

**Note: _In the previous test, the paged request was not done_**

Tested in version: **62.3-20190603**

**Comment by mprevide** [comment]
Probily associate a #1181

**Comment by mprevide** [comment]
```
version: '2.1'
services:

  history:
    image: dojot/history:63.1-20190705
    restart: always
    depends_on:
      - mongodb
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_MANAGEMENT_USER: 'history'
    logging:
      driver: json-file
      options:
        max-size: 100m

  persister:
    image: dojot/persister:63.1-20190705
    restart: always
    depends_on:
      - mongodb
      - auth
      - kafka
      - data-broker
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_MANAGEMENT_USER: 'persister'
      KAFKA_GROUP_ID: 'persister-group'
    logging:
      driver: json-file
      options:
        max-size: 100m

  mongodb:
    image: "mongo:3.2"
    restart: always
    user: "mongodb"
    logging:
      driver: json-file
      options:
        max-size: 100m

  mosca-redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  iotagent-mqtt:
    image: dojot/iotagent-mosca:63.1-20190705
    depends_on:
      - mosca-redis
      - kafka
      - data-broker
      - auth
      - ejbca
    ports:
      - 1883:1883
      - 8883:8883
    restart: always
    environment:
      DOJOT_MANAGEMENT_USER: 'iotagent-mqtt'
      KAFKA_GROUP_ID: 'iotagent-mqtt-group'
      ALLOW_UNSECURED_MODE: 'false'
    logging:
      driver: json-file
      options:
        max-size: 100m

  gui:
    image: dojot/gui:release_63.1-20190705
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  data-broker:
    image: dojot/data-broker:63.1-20190705
    restart: always
    depends_on:
      - kafka
      - data-broker-redis
    environment:
      DOJOT_MANAGEMENT_USER: 'data-broker'
      KAFKA_GROUP_ID: 'data-broker-group'
    logging:
      driver: json-file
      options:
        max-size: 100m

  data-broker-redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  device-manager-redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

################
# iot-agent lwm2m
################
  iotagent-lwm2m:
    image: dojot/iotagent-leshan:63.1-20190705
    depends_on:
      - kafka
      - data-broker
      - auth
      - image-manager
    environment:
      DOJOT_MANAGEMENT_USER: 'iotagent-lwm2m'
      KAFKA_GROUP_ID: "iotagent-lwm2m-group"
      # The FILE_SERVER_ADDRESS should be filled with an address accesible to the devices that want to update the firmware
      FILE_SERVER_ADDRESS: 127.0.0.1
    ports:
      - 5683:5683/udp # configuration coap port
      - 5684:5684/udp # configuration dtls port
      - 5693:5693/udp # file server coap port
      - 5694:5694/udp # file server dtls port
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  image-manager:
    image: dojot/image-manager:63.1-20190705
    restart: always
    depends_on:
      - postgres
      - minio
    logging:
      driver: json-file
      options:
        max-size: 100m
    environment:
      # TODO: The following should be unique for each environment
      S3ACCESSKEY: 9HEODSF6WQN5EZ39DM7Z
      S3SECRETKEY: fT5nAgHR9pkj0yYsBdc4p+PPq6ArjshcPdz0HA6W

  minio:
    image: "minio/minio"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m
    environment:
      # TODO: The following should be unique for each environment
      MINIO_ACCESS_KEY: 9HEODSF6WQN5EZ39DM7Z
      MINIO_SECRET_KEY: fT5nAgHR9pkj0yYsBdc4p+PPq6ArjshcPdz0HA6W
    command: server /data

  device-manager:
    image: dojot/device-manager:63.1-20190705
    restart: always
    environment:
      # TODO: Fill these env variables with suitable values
      - DEV_MNGR_CRYPTO_PASS="kamehameHA"
      - DEV_MNGR_CRYPTO_IV=1234567890123456
      - DEV_MNGR_CRYPTO_SALT="shuriken"
    depends_on:
      - postgres
      - kafka
      - data-broker
      - device-manager-redis
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth-redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth:
    image: dojot/auth:63.1-20190705
    restart: always
    depends_on:
      - apigw
      - postgres
      - auth-redis
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AUTH_DB_HOST: "postgres"
      AUTH_DB_USER: "kong"
      AUTH_KONG_URL: "http://apigw:8001"
      AUTH_CACHE_HOST: "auth-redis"
      # This is used to select the type of cache to be used. Allowed values are "redis" or "nocache"
      AUTH_CACHE_NAME: "redis"
      DOJOT_MANAGEMENT_USER: 'auth'
      KAFKA_GROUP_ID: 'auth-group'
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres:
    image: "postgres:9.4-alpine"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres-users:
    image: "postgres:9.4-alpine"
    restart: on-failure
    command: >
      bash -c "if ! psql -h postgres -U postgres -t -c '\du' | cut -d \| -f 1 | grep -qw kong; then
                   echo 'creating user kong'
                   createuser kong -d -h postgres -U postgres
               else
                   echo 'user kong exists'
               fi
               if ! psql -h postgres -U postgres -lqt | cut -d \| -f 1 | grep -qw kong; then
                   echo 'creating database kong'
                   createdb kong -U kong -h postgres
               else
                   echo 'database kong exists'
               fi"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-migration:
    image: dojot/kong:63.1-20190705
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
    command: kong migrations up
    restart: on-failure

  apigw:
    image: dojot/kong:63.1-20190705
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres"
    volumes:
      - ./apigw/plugins/pep-kong:/plugins/pep-kong:Z
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-config:
    image: appropriate/curl
    entrypoint: /opt/kong.config.sh
    restart: on-failure
    depends_on:
      - apigw
    volumes:
      - ./kong.config.sh:/opt/kong.config.sh:Z

  flowbroker-redis:
    image: redis:alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  flowbroker:
    image: dojot/flowbroker:63.1-20190705
    restart: always
    environment:
      DEPLOY_ENGINE: "docker"
      FLOWBROKER_NETWORK: ${FLOWBROKER_NETWORK}
      DOJOT_MANAGEMENT_USER: 'flowbroker'
      KAFKA_GROUP_ID: 'flowbroker-group'
    depends_on:
      - rabbitmq
      - kafka
      - mongodb
      - auth
      - flowbroker-context-manager
      - flowbroker-redis
    networks:
      - default
      - flowbroker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z

  flowbroker-context-manager:
    image: dojot/flowbroker-context-manager:63.1-20190705
    restart: always
    environment:
      ZOOKEEPER_HOST: zookeeper
      ZOOKEEPER_PORT: 2181
      ZEROMQ_PORT: 5556
      HOLD_LOCK_TIMEOUT: 10000
      WAIT_LOCK_TIMEOUT: 30000
    depends_on:
      - zookeeper
    networks:
      - default
      - flowbroker

  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  zookeeper:
    image: "zookeeper:3.4"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafka:
    image: "wurstmeister/kafka:2.12-2.1.1"
    depends_on:
      - zookeeper
    restart: always
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_NUM_PARTITIONS: 10
      JMX_PORT: 1099
    logging:
      driver: json-file
      options:
        max-size: 100m

  ejbca:
    image: "dojot/ejbca-rest:63.1-20190705"
    environment:
      DOJOT_MANAGEMENT_USER: 'ejbca'
      KAFKA_GROUP_ID: 'ejbca-group'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m


  data-manager:
    image: "dojot/data-manager:63.1-20190705"
    restart: always
    depends_on:
      - flowbroker
      - device-manager

  backstage:
    image: "dojot/backstage:63.1-20190705"
    restart: always
    depends_on:
      - postgres

  cron:
    image: dojot/cron:63.1-20190705
    depends_on:
      - kafka
      - data-broker
      - auth
      - mongodb
    ports:
      - 5000:5000
    restart: always

networks:
  flowbroker:
    name: ${FLOWBROKER_NETWORK}

```
