### ISSUE TITLE
[ansible] not expose kong admin port

### ISSUE THREAD

**Issue by mprevide** [dojot/dojot#1470]
ansible-dojot/roles/apigw/templates/apigw_external_service.yaml.j2

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: kong-external
  name: kong-external
  namespace: {{ dojot_namespace }}
spec:
  type: NodePort
  ports:
  - name: "apigw-http"
    port: {{ dojot_internal_http_port }}
    targetPort: {{ dojot_internal_http_port }}
    nodePort: 30001
  selector:
    name: kong
    app: dojot
```

ansible-dojot/roles/apigw/templates/apigw_internal_service.yaml.j2

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: kong
  name: kong
  namespace: {{ dojot_namespace }}
spec:
  type: ClusterIP
  ports:
  - name: "apigw-config"
    port: {{ dojot_internal_api_config_port }}
    targetPort: {{ dojot_internal_api_config_port }}
  - name: "apigw-http-internal"
    port: {{ dojot_internal_http_port }}
    targetPort: {{ dojot_internal_http_port }}
  selector:
    name: kong
    app: dojot

```
