### ISSUE TITLE
Unnable to publish with mosquitto_pub

### ISSUE THREAD

**Issue by scherly** [dojot/dojot#1474]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **What is the current behavior?**

When I try to publish using

`mosquitto_pub -h localhost -t "/admin/f76e4d/attrs" -m '{"humidity" : 10.0}'`

I get: `Error: The connection was lost.`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I do not know if this is a bug, but what I did is to follow the steps on [https://dojotdocs.readthedocs.io/en/v0.4.2/using-web-interface.html]()

I created the template, the device and tried to send a message to the device using mosquitto_pub.

I ensured that ALLOW_UNSECURED_MODE is set to 'true' in the docker-commpose.yml file, as shown in [https://github.com/dojot/docker-compose/issues/129](#issue 129). Moreover, there is no mosquitto running when I do `ps aux | grep mosquitto`

* **What is the expected behavior?**

After mosquitto_pub, the "humidity" attribute of my device "f76e4d" should change to "10.0", and the attribute graph should be updated.

* **Please tell us about your environment:**
  
  - Version: 0.4.2
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 20.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

When I try to use the mosquitto_pub command with a public broker and sub to the same topic, I can see the published information.

**Comment by mprevide** [comment]
Try to run  `mosquitto_pub -h localhost -p 1883 -t "/admin/f76e4d/attrs" -m '{"humidity" : 10.0}'` or `mosquitto_pub -h localhost -p 1883 -t "/admin/f76e4d/attrs" -m '{"humidity" : 10.0}' -i admin:f76e4d`

**Comment by scherly** [comment]
Hi Mariane, I tried these commands, but the same happened.

![dojot-mqtt](https://user-images.githubusercontent.com/46680123/83163820-d92e5700-a0e1-11ea-9d51-60534a3a4c32.png)

This is part of my docker-compose.yml file.

```
version: '2.1'
services:

  history:
    image: dojot/history:v0.4.2
    restart: always
    depends_on:
      - mongodb
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_MANAGEMENT_USER: 'history'
    logging:
      driver: json-file
      options:
        max-size: 100m

  persister:
    image: dojot/persister:v0.4.2
    restart: always
    depends_on:
      - mongodb
      - auth
      - kafka
      - data-broker
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
      DOJOT_MANAGEMENT_USER: 'persister'
      KAFKA_GROUP_ID: 'persister-group'
    logging:
      driver: json-file
      options:
        max-size: 100m

  mongodb:
    image: dojot/mongo:3.2
    restart: always
    user: "mongodb"
    logging:
      driver: json-file
      options:
        max-size: 100m

  mosca-redis:
    image: dojot/redis:5.0.5-alpine3.10
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  iotagent-mqtt:
    image: dojot/iotagent-mosca:v0.4.2
    depends_on:
      - mosca-redis
      - kafka
      - data-broker
      - auth
      - ejbca
    ports:
      - 1883:1883
      - 8883:8883
    restart: always
    environment:
      DOJOT_MANAGEMENT_USER: 'iotagent-mqtt'
      KAFKA_GROUP_ID: 'iotagent-mqtt-group'
      ALLOW_UNSECURED_MODE: 'true'
      MOSCA_TLS_DNS_LIST: 'localhost'
    logging:
      driver: json-file
      options:
        max-size: 100m
```
I also attach part of a log file. Apparently there are some strange things happening with the iot agent but I can't understand it.

[dojot-log.txt](https://github.com/dojot/dojot/files/4696801/dojot-log.txt)

**Comment by mprevide** [comment]
![image](https://user-images.githubusercontent.com/6900446/83206907-52509d00-a128-11ea-9ad8-47f2af3fd044.png)

In this image I could see that the door 1883 is already being used, probably by the mosquitto service. I believe that you have installed and are running the mosquitto service. You just need to install mosquitto-clients to publish and sub.

Run `docker-compose down` and uninstall the mosquitto service or deallocate the service that is using the same port 1883 and then run`docker-compose up -d`.

Another option is to switch the port that is exported, you can change it in docker-compose.yml, in the line that is `-1883: 1883`, change to another port like` - 5883: 1883`, so when using `mosquitto_pub `or` mosquitto_sub` pass `-p 5883`.

Note: Remember to give `docker-compose down` and` docker-compose up -d` when making any changes to docker-compose.

**Comment by mprevide** [comment]
Try to run `sudo netstat -tulnp | grep 1883` to see what is running on the port.

**Comment by mprevide** [comment]
The log is strange, it seems that the service is not going up. 
What version of docker-compose and docker are you using? 
Do you have space on your disk?

**Comment by scherly** [comment]
> ![image](https://user-images.githubusercontent.com/6900446/83206907-52509d00-a128-11ea-9ad8-47f2af3fd044.png)
> 
> In this image I could see that the port 1883 is already being used, probably by the mosquitto service. I believe that you have installed and are running the mosquitto service. You just need to install mosquitto-clients ( `sudo apt-get install mosquitto-clients`) to publish and sub.
> 
> Run `docker-compose down` and uninstall ( `sudo apt-get uninstall mosquitto`) the mosquitto service or unbind the service that is using the same port 1883 and then run`docker-compose up -d`.
> 
> Another option is to switch the port that is exported, you can change it in docker-compose.yml, in the line that is `-1883: 1883`, change to another port like` - 5883: 1883`, so when using `mosquitto_pub `or `mosquitto_sub` pass `-p 5883`.
> 
> Note: Remember to give `docker-compose down` and` docker-compose up -d` when making any changes to docker-compose.

Yes it was in use by the Ubuntu's mosquitto broker, but I stopped it before going up with the docker again. Ayway I already uninstalled the "mosquitto" and let only the mosquitto-clients. The result was the same.

As for changing the port in the docker-compose.yml, docker down, docker up, and running `mosquitto_pub -h localhost -p 5883 -t "/admin/f76e4d/attrs" -m '{"humidity" : 10.0}'` I got a different message: "connection refused"

**Comment by scherly** [comment]
> The log is strange, it seems that the service is not going up.
> What version of docker-compose and docker are you using?
> Do you have space on your disk?

Yes, the log is kind of bizarre. The versions are:

`dianne@persian:~/dojot/docker-compose$ docker --version
Docker version 19.03.8, build afacb8b7f0`

`dianne@persian:~/dojot/docker-compose$ docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6`

I'm using a virtual machine with 40 GB. As for now I have 18 GB of free space. (and the host machine has also free space)

**Comment by mprevide** [comment]
Try to kill everything `sudo docker rm -f $ ($ docker ps -qa)`, then clear any `sudo docker volume prune` volume and ` sudo docker system prune -a` image.

Then start up again`sudo docker-compose up -d `.

Create your template and device, try publishing to port 5883 with something like `mosquitto_pub -h localhost -p 5883 -t  /admin/f76e4d/attrs  -m '{" humidity ": 10.0}'  -i admin: f76e4d`

And take the logs separately from ejbca and mqtt, for this:
`sudo docker-compose logs ejbca` and `sudo docker-compose logs iotagent-mqtt` and attach here.

**Comment by mprevide** [comment]
> Try to run `mosquitto_pub -h localhost -p 1883 -t /admin/f76e4d/attrs -m '{"humidity" : 10.0}'` or `mosquitto_pub -h localhost -p 1883 -t /admin/f76e4d/attrs -m '{"humidity" : 10.0}' -i admin:f76e4d`

In this comment I copied your example, and I didn't realize that the topic was in quotes, I fixed it.

**Comment by scherly** [comment]
> Try to kill everything `sudo docker rm -f $(docker ps -qa)`, then clear any `sudo docker volume prune` volume and `sudo docker system prune -a` image.
> 
> Then start up again`sudo docker-compose up -d `.
> 
> Create your template and device, try publishing to port 5883 with something like `mosquitto_pub -h localhost -p 5883 -t /admin/f76e4d/attrs -m '{" humidity ": 10.0}' -i admin:f76e4d` (Run on the vm the docker-compose is running on.)

Done everything, and back to the "connection lost" :(

![dojot-pub](https://user-images.githubusercontent.com/46680123/83287862-c63a8600-a1b8-11ea-83b7-d5eb2fd5fde5.png)

> And take the logs separately from ejbca and mqtt, for this:
> `sudo docker-compose logs ejbca` and `sudo docker-compose logs iotagent-mqtt` and attach here.
> 

[dojot-log-ejbca.txt](https://github.com/dojot/dojot/files/4703303/dojot-log-ejbca.txt)
[dojot-log-full.txt](https://github.com/dojot/dojot/files/4703304/dojot-log-full.txt)


> What changes have you made to the docker-compose.yml file?

I changed the following lines on the "iotagent-mqtt"
```
     - 5883:1883
     ALLOW_UNSECURED_MODE: 'true'

```
 
> Thank you smile_cat

I'm the one who must thank you for the attention!

**Comment by mprevide** [comment]
> ![image](https://user-images.githubusercontent.com/6900446/83206907-52509d00-a128-11ea-9ad8-47f2af3fd044.png)
> 
Sorry, just now I saw that you had already stopped the mosquito service.

**Comment by mprevide** [comment]
We will investigate the problem. 

I cannot reproduce the problem immediately. We will need to investigate.

I hope to return soon.
thank you again

**Comment by mprevide** [comment]
Just to confirm, in your docker-compose.yml there is the snippet below and the image is `dojot/ejbca-rest:v0.4.2`, right?

```yml
  ejbca:
    image: dojot/ejbca-rest:v0.4.2
    environment:
      DOJOT_MANAGEMENT_USER: 'ejbca'
      KAFKA_GROUP_ID: 'ejbca-group'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m
```

**Comment by scherly** [comment]
> Just to confirm, in your docker-compose.yml there is the snippet below and the image is `dojot/ejbca-rest:v0.4.2`, right?
> 
> ```yaml
>   ejbca:
>     image: dojot/ejbca-rest:v0.4.2
>     environment:
>       DOJOT_MANAGEMENT_USER: 'ejbca'
>       KAFKA_GROUP_ID: 'ejbca-group'
>     restart: always
>     logging:
>       driver: json-file
>       options:
>         max-size: 100m
> ```

Yes! Just like yours.
```


  ejbca:
    image: dojot/ejbca-rest:v0.4.2
    environment:
      DOJOT_MANAGEMENT_USER: 'ejbca'
      KAFKA_GROUP_ID: 'ejbca-group'
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m
```

I will just let here all the steps with all the commands I ran to install the dojot via docker-compose. Again I'm using a virtual machine on Virtual Box, running Ubuntu 20.04, Docker version 19.03.8, build afacb8b7f0, and docker-compose version 1.25.5, build 8a1c60f6

This is what I did step-by-step, and what my students are trying to do (there are 2 with the same problem, but one running a "real" Ubuntu 18.04, and the other running a VM Ubuntu 18.04)

### DOCKER
```
$ sudo apt-get remove docker docker-engine docker.io containerd runc
$ sudo apt install docker.io
$ sudo systemctl enable --now docker
$ sudo docker --version
$ sudo docker run hello-world
$ sudo usermod -aG docker dianne

```
Log out  then log in

### DOCKER-COMPOSE

```
sudo apt install py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
sudo apt install python-dev libffi-dev gcc libc-dev make curl
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose --version
```

### DOJOT

```
$ mkdir dojot
$ cd dojot/
$ git clone https://github.com/dojot/docker-compose.git
$ cd docker-compose/
$ git checkout v0.4.2 -b v0.4.2
$ vim docker-compose.yml

```
(change ALLOW_UNSECURED_MODE: 'false' to ALLOW_UNSECURED_MODE: 'true')
(change  - 1883:1883 to - 5883:1883)

`$ docker-compose up -d`

### MOSQUITTO PUB/SUB

`$ sudo apt install mosquitto-clients`

### TRY TO MQTT PUB DOJOT

create template, create device (fresh installation different from the one I started with in this thread, now using another sensor template/device)

`$ mosquitto_pub -h localhost -p 5883 -t /admin/129f49/attrs -m '{" temp ": 10.0}' -i admin:129f49`
(results in Error: connection was lost)

**Comment by mprevide** [comment]
Just another simple test, did you try to kill and up the ejbca again after this error?
`sudo docker-compose kill ejbca` and` sudo docker-compose up -d ejbca`

**Comment by thiagodpf** [comment]
> > Try to kill everything `sudo docker rm -f $(docker ps -qa)`, then clear any `sudo docker volume prune` volume and `sudo docker system prune -a` image.
> > Then start up again`sudo docker-compose up -d `.
> > Create your template and device, try publishing to port 5883 with something like `mosquitto_pub -h localhost -p 5883 -t /admin/f76e4d/attrs -m '{"humidity": 10.0}' -i admin:f76e4d` (Run on the vm the docker-compose is running on.)
> 
> Done everything, and back to the "connection lost" :(
> 
> ![dojot-pub](https://user-images.githubusercontent.com/46680123/83287862-c63a8600-a1b8-11ea-83b7-d5eb2fd5fde5.png)
> 
> > And take the logs separately from ejbca and mqtt, for this:
> > `sudo docker-compose logs ejbca` and `sudo docker-compose logs iotagent-mqtt` and attach here.
> 
> [dojot-log-ejbca.txt](https://github.com/dojot/dojot/files/4703341/dojot-log-ejbca.txt)
> [dojot-log-mqtt.txt](https://github.com/dojot/dojot/files/4703342/dojot-log-mqtt.txt)
> 
> EJBCA seems to stop after a few minutes. This is probably the reason why the iotagent informs that it can't connect to the EJBCA
> 
> > What changes have you made to the docker-compose.yml file?
> 
> I changed the following lines on the "iotagent-mqtt"
> 
> ```
>      - 5883:1883
>      ALLOW_UNSECURED_MODE: 'true'
> ```
> 
> > Thank you smile_cat
> 
> I'm the one who must thank you for the attention!

Hello! 
Could you check for logs inside the EJBCA container? 

docker exec --user root -it **ejbca-container-name** /bin/bash

this runs on a wildfly and theoretically the logs should be in the directory:
/opt/primekey/**appserver/standalone/log**

When wildfly fails during a .ear deployment, it leaves a mini tip of what happened in the file:
/opt/primekey/appserver/standalone/deployments/ejbca.ear **.failed**

This **ejbca.ear.failed** file is only generated when wildfly was unable to deploy the ejbca application's .ear, so in your case, there will probably be a _.failed_ there

**Comment by mprevide** [comment]
> ejbca-container-name

**Comment by mprevide** [comment]
> docker exec --user root -it **ejbca-container-name** /bin/bash

**ejbca-container-name**  is dojot_ejbca_1 in this case

**Comment by scherly** [comment]
> Just another simple test.
> Did you try to kill and up only the ejbca again after this error in ejbca?
> `sudo docker-compose kill ejbca` and` sudo docker-compose up -d ejbca`


You are the boss! 

![dojot-working](https://user-images.githubusercontent.com/46680123/83418014-44856b00-a3f9-11ea-800c-5a361d05cc94.png)

Thank you very much!! I will try to replicate this with my students tomorrow. Hope it works. Probably it will.

Regarding the ejbca.ear.failed that Thiago asked for, indeed it is there when I can't pub with mosquitto_pub. I checked the file and it says `JBAS015052: Did not receive a response to the deployment operation within the allowed timeout period [60 seconds]. Check the server configuration file and the server logs to find more about the status of the deployment.`

When I kill ejbca, and then up -d it, the ".failed" file is not there anymore.

**Comment by mprevide** [comment]
> > Just another simple test.
> > Did you try to kill and up only the ejbca again after this error in ejbca?
> > `sudo docker-compose kill ejbca` and` sudo docker-compose up -d ejbca`
> 
> You are the boss!
> 
> ![dojot-working](https://user-images.githubusercontent.com/46680123/83418014-44856b00-a3f9-11ea-800c-5a361d05cc94.png)
> 
> Thank you very much!! I will try to replicate this with my students tomorrow. Hope it works. Probably it will.
> 
> Regarding the ejbca.ear.failed that Thiago asked for, indeed it is there when I can't pub with mosquitto_pub. I checked the file and it says `JBAS015052: Did not receive a response to the deployment operation within the allowed timeout period [60 seconds]. Check the server configuration file and the server logs to find more about the status of the deployment.`
> 
> When I kill ejbca, and then up -d it, the ".failed" file is not there anymore.

:smiley:  Great!

But you found a bug and we will fix it asap.

Thank you very much!!

**Comment by thiagodpf** [comment]
> > Just another simple test.
> > Did you try to kill and up only the ejbca again after this error in ejbca?
> > `sudo docker-compose kill ejbca` and` sudo docker-compose up -d ejbca`
> 
> You are the boss!
> 
> ![dojot-working](https://user-images.githubusercontent.com/46680123/83418014-44856b00-a3f9-11ea-800c-5a361d05cc94.png)
> 
> Thank you very much!! I will try to replicate this with my students tomorrow. Hope it works. Probably it will.
> 
> Regarding the ejbca.ear.failed that Thiago asked for, indeed it is there when I can't pub with mosquitto_pub. I checked the file and it says `JBAS015052: Did not receive a response to the deployment operation within the allowed timeout period [60 seconds]. Check the server configuration file and the server logs to find more about the status of the deployment.`
> 
> When I kill ejbca, and then up -d it, the ".failed" file is not there anymore.

Thanks for the feedback, these problems only appear when the dojot is put to the real test, so we did not anticipate it. sorry.

From what I've investigated here regarding this error message from the Wildfly application server, it appears that this problem is usual in overloaded environments. you can try increasing the **deployment-timeout** in the _standalone.xml_ 
(inside the EJBCA container: /opt/primekey/appserver/standalone/configuration/standalone.xml)

Find This block (subsystem _deployment-scanner_)
```xml
<subsystem xmlns="urn:jboss:domain:deployment-scanner:2.0">
    <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" scan-interval="0" deployment-timeout="600"
        runtime-failure-causes-rollback="${jboss.deployment.scanner.rollback.on.failure:false}" auto-deploy-exploded="true"/>
</subsystem>
```

Then add (or edit) the _attribute_ **deployment-timeout** (in seconds) to a value like 10 minutes (600sec), or some value that best suits your hardware configuration
```xml
<subsystem xmlns="urn:jboss:domain:deployment-scanner:2.0">
    <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" scan-interval="0"
        runtime-failure-causes-rollback="${jboss.deployment.scanner.rollback.on.failure:false}" auto-deploy-exploded="true"
        deployment-timeout="600" />
</subsystem>
```

**Comment by scherly** [comment]
I added the deployment-timeout="600" here:

```
       </subsystem>                           
        <subsystem xmlns="urn:jboss:domain:deployment-scanner:1.1">
            <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" scan-interval="5000" deployment-timeout="600"/>
        </subsystem>   
```
and it worked fine. Except for...I lost the configured devices, templates and flows. The only thing I changed from yesterday was this line. But maybe it was a coincidence.

**Comment by thiagodpf** [comment]
This configuration section should not impact the other dojot services, this configuration affects only the Wildfly application server that runs the EJBCA, which in turn has the purpose of generating x.509 certificates only.

What may have happened is that the docker-compose has lost reference to the volumes where the database service persisted the data.
If the dojot service stack is terminated via docker-compose with the command:: `docker-compose down -v`  it removes the volumes, then you lose all the data, but otherwise, if the volumes still exist, it is possible to recover the data, but it will be hard work.

If you prefer, there is a utility called Portainer that shows you all the docker volumes (among other things) on your computer: https://www.portainer.io/
Perhaps there you will be able to reassign the volumes to the database services, but this is something that I do not have so much domain to help.

**Comment by mprevide** [comment]
> I lost the configured devices, templates and flows. The only thing I changed from yesterday was this line. But maybe it was a coincidence.

To avoid data loss when docker-compose down, you can create volumes, like this:

```yaml 
   postgres:
    image: dojot/postgres:9.4.24-alpine
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data  
    logging:
      driver: json-file
      options:
        max-size: 100m

  mongodb:
    image: dojot/mongo:3.2
    restart: always
    user: "mongodb"
    volumes:
      - mg-data:/data/db      
    logging:
      driver: json-file
      options:
        max-size: 100m

    volumes:
       mg-data:
       pg-data: 
```
Basically you should change de docker-compose.yml:

```yaml 
   ....
    volumes:
      - mg-data:/data/db    
    ...
    volumes:
      - pg-data:/var/lib/postgresql/data  
   ...

    # end of file
    volumes:
       mg-data:
       pg-data: 
```
