### ISSUE TITLE
Change default value for persistence (volumes - docker compose)

### ISSUE THREAD

**Issue by bizetti** [dojot/dojot#1484]
See PR https://github.com/dojot/docker-compose/pull/147/files

For version 0.4.x

**Comment by thiagodpf** [comment]
PR that maps volumes to the docker-compose:
https://github.com/dojot/docker-compose/pull/156

**Comment by betefaber** [comment]
Tested in **v0.4.3-rc.2**:

- volumes mapped in the docker-compose environment:
```
volumes:
  postgres-volume:
  postgres-users-volume:
  mongodb-volume:
  mongodb-cfg-volume:
  ejbca-volume:
  minio-volume:
  rabbitmq-volume:
  zookeeper-volume:
  zookeeper-logs-volume:
  zookeeper-datalog-volume:
  kafka-volume:
  auth-redis-volume:
  flowbroker-volume:
  flowbroker-redis-volume:
  data-broker-redis-volume:
  device-manager-redis-volume:
  mosca-redis-volume:
```

- fix kafka hostname

**Comment by betefaber** [comment]
Tested in **v0.5.0-rc.1**

- volumes mapped in the docker-compose environment:

```
volumes:
  ejbca-volume:
  postgres-volume:
  mongodb-volume:
  mongodb-cfg-volume:
  minio-volume:
  rabbitmq-volume:
  zookeeper-volume:
  zookeeper-log-volume:
  zookeeper-secrets-volume:
  kafka-volume:
  kafka-secrets-volume:
  iotagent-mqtt-volume:
  iotagent-mqtt-log-volume:
  iotagent-mqtt-etc-volume:
  auth-redis-volume:
  flowbroker-volume:
  flowbroker-redis-volume:
  data-broker-redis-volume:
  device-manager-redis-volume:
  kafka-ws-redis-volume:
  mosca-redis-volume:
```

-  added the x509-identity-mgmt and kafka-ws components
- fixed kafka hostname
