### ISSUE TITLE
[x509] Error when uploading a new version without deleting the volumes

### ISSUE THREAD

**Issue by FrancielePessi** [dojot/dojot#2043]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Local machine was running a previous version, when dropped without erasing the volumes, an error occurred when uploading a new version v0.6.0-rc.2.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**1º** To be with a version currently running.

**2º** Use the **docker-compose down** command.

**3º** Download the new version and upload **(docker-compose up)**.

* **What is the expected behavior?**
* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: v0.6.0-rc.2
  - Environment: [docker-compose]
  - Operating system: [Ubuntu 18.04]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

_____

![Captura de tela de 2021-03-23 12-03-47.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/ba401877-4529-4559-a310-fbd8429aaeaf)

**Comment by mprevide** [comment]
Two people reported the same problem. @luisfelipefurlan  @cfrancisco 
Luis when migrating from v0.5 to v0.5.2 using docker-compose

**Comment by thiagodpf** [comment]
To be compatible with the previous version, the following environment variable must be included:
`EJBCA_INTERNAL_CA: "Services CA"`

The definition of the service in the docker-compose file is as follows:
```yaml
  x509-identity-mgmt:
    image: dojot/x509-identity-mgmt:v0.6.0-rc.2
    depends_on:
      - postgres
      - mongodb
    restart: always
    hostname: "x509-identity-mgmt"
    domainname: "dojot.iot"
    environment:
      DATABASE_JDBC_URL: jdbc:postgresql://postgres:5432/ejbca?characterEncoding=UTF-8
      DATABASE_USER: ejbca
      DATABASE_PASSWORD: ejbca
      EJBCA_PERFORM_DOJOT_SETUP: "true"
      NODE_ENV: production
      MONGO_URI: "mongodb://mongodb:27017/x509-identity-mgmt"
      EJBCA_INTERNAL_CA: "Services CA"
    volumes:
      - ejbca-volume:/mnt/persistent
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '5'
```
