### ISSUE TITLE
Service and Device id - aikido

### ISSUE THREAD

**Issue by danielnunesdeoliveira** [dojot/dojot#439]
In new version I do not find:
- Device ID;
- Service;
/<service-id>/<device-id>/attrs

**Comment by giovannicuriel** [comment]
Hi!

We are working on that. The device ID was added to the web interface in #422. 
The service pull-requests will be gathered by dojot/gui#140.

The device ID can be retrieved in two ways: using the 0.2.0 tag, you could check it out in the link of the device detail page: 

![captura de tela em 2018-04-17 14-39-52](https://user-images.githubusercontent.com/6285982/38891670-69290874-425b-11e8-967c-11c6c843fcef.png)

Note that the link is .../device/id/*817e36*/detail

Another way is to update the GUI container to a newer (but still in testing) container. Just change the GUI section in docker-compose.yml to 
```
  gui:
     image: dojot/gui:0.3.0-nightly20180416
     restart: always
     logging:
       driver: json-file
       options:
         max-size: 100m
```
(The tabs are important)
Therefore, there will be a new field which is the device ID (also shown in the image).
